server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
//<<< API Gateway / Routes
      routes:

        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: order_websocket
          uri: http://localhost:7082
          predicates:
            - Path=/rsocket/orders

        - id: product
          uri: http://localhost:8083
          predicates:
            - Path=/products/**, 
        - id: product_websocket
          uri: http://localhost:7083
          predicates:
            - Path=/rsocket/products

        - id: delivery
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/**, 
        - id: delivery_websocket
          uri: http://localhost:7084
          predicates:
            - Path=/rsocket/deliveries

        
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
//>>> API Gateway / Routes

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/products/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
